### ISSUE TITLE
n the project roadmap to be displayed the total number of test cases from the existing execution suites for a certain version

### ISSUE THREAD

**Issue by marius-balteanu** [sdwolf/redcaser#10]
Currently for a certain version it's displayed:
Total test cases: 0 [Passed=0] [Failed=0] [Blocked=0]

Expected:
- Given that you have multiple execution suites for a certain version.
  Example: 
  "Exec suite 1" with a total of 5 test cases (Passed = 4; Failed = 0; Blocked = 0, Not run = 1)
  "Exec suite 2" with a total of 5 test cases (Passed = 1; Failed = 1; Blocked = 1, Not run = 2)
- When you go to the project Roadmap for a certain version the total number of test cases will be displayed
  Example:
  Total test cases: 10 [Passed=5] [Failed=1] [Blocked=1]

https://github.com/marius-balteanu/redmine_redcaser/blob/master/lib/redmine_redcaser/hooks/override_hook.rb#L137

**Comment by cody-vibe** [comment]
Fixed on master, you may need to remove all TestCaseStatus entries since a bug allowed duplicating them.
