### ISSUE TITLE
Campul test_suite ar trebui sa fie obligatoriu la adaugarea unui test case nou

### ISSUE THREAD

**Issue by marius-balteanu** [sdwolf/redcaser#7]
- Mergi pe un proiect fara test suite-uri
- Adauga un nou test case 
- Observa ca test case-ul s-a adaugat cu succes.

Ar trebui sa validam acel camp

**Comment by cody-vibe** [comment]
Implemented in 207392ec7a6f0fb6875fceb78fcec78e6d0ae8f0.
